# Generated by Django 4.2.1 on 2024-05-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contract_description_contract_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.AddField(
            model_name='contract',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='main.contractrole', verbose_name='Роли имеющие доступ к контракту'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.contractrole', verbose_name='Роль'),
            preserve_default=False,
        ),
    ]
