# Generated by Django 4.2.1 on 2024-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='main.contractrole', verbose_name='Роли пользователя'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.TextField(default='Контракт', verbose_name='Имя'),
        ),
    ]
